services:
  index-tts2:
    image: your-repo/index-tts2:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - INDEXTTS_AUTOWARM=true
    ports:
      - "8000:8000"
    volumes:
      - ./voices:/app/voices
      - ./output:/app/output
      - ./models:/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
